### PR TITLE
Deep roboy feature

### PR DESCRIPTION
**Pull request by tomasruizt**

### CODE REVIEW

**Comment by BarisYazici** [comment]
I have changed some messages in the past. In order to solve the merge conflicts before midterm. If we merge with master those conflicts will be an issue.

**Comment by tomasruizt** [comment]
yes. Is it possible to resolve the conflicts?

**Comment by BarisYazici** [comment]
No unless we change the robot.cpp going through Simon’s code.

**Comment by BarisYazici** [comment]
Is it possible to create this deb package baeed on our branch?

**Pull request merged**
